2019-05-27 23:10:02,091 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-27 23:10:07,266 level=INFO message=127.0.0.1 - - [27/May/2019 23:10:07] "GET /help HTTP/1.1" 200 -
2019-05-27 23:10:09,117 level=INFO message=127.0.0.1 - - [27/May/2019 23:10:09] "GET /help HTTP/1.1" 200 -
2019-05-27 23:10:13,349 level=INFO message=127.0.0.1 - - [27/May/2019 23:10:13] "GET / HTTP/1.1" 200 -
2019-05-28 21:06:46,066 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-28 21:07:32,179 level=ERROR message=MySQL connection is NOT OK!
2019-05-28 21:07:32,182 level=INFO message=127.0.0.1 - - [28/May/2019 21:07:32] "POST /add HTTP/1.1" 200 -
2019-05-28 21:07:52,952 level=ERROR message=Not Found
2019-05-28 21:07:52,953 level=INFO message=127.0.0.1 - - [28/May/2019 21:07:52] "GET /list/2 HTTP/1.1" 200 -
2019-05-28 21:07:57,205 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 67, in list
    cur = mysql.connection.cursor()
AttributeError: 'MySQL' object has no attribute 'connection'
2019-05-28 21:07:57,210 level=INFO message=127.0.0.1 - - [28/May/2019 21:07:57] "GET /list HTTP/1.1" 500 -
2019-05-28 21:08:00,091 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 67, in list
    cur = mysql.connection.cursor()
AttributeError: 'MySQL' object has no attribute 'connection'
2019-05-28 21:08:00,094 level=INFO message=127.0.0.1 - - [28/May/2019 21:08:00] "GET /list HTTP/1.1" 500 -
2019-05-28 21:09:34,906 level=ERROR message=MySQL connection is NOT OK!
2019-05-28 21:09:34,907 level=INFO message=127.0.0.1 - - [28/May/2019 21:09:34] "POST /add HTTP/1.1" 200 -
2019-05-28 21:11:52,232 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 67, in list
    cur = mysql.connection.cursor()
AttributeError: 'MySQL' object has no attribute 'connection'
2019-05-28 21:11:52,235 level=INFO message=127.0.0.1 - - [28/May/2019 21:11:52] "GET /list HTTP/1.1" 500 -
2019-05-28 21:27:47,671 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-28 21:28:12,359 level=ERROR message=MySQL connection is NOT OK!
2019-05-28 21:28:12,364 level=INFO message=127.0.0.1 - - [28/May/2019 21:28:12] "POST /add HTTP/1.1" 200 -
2019-05-28 21:28:20,149 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 67, in list
    cur = mysql.connection.cursor()
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1044, "Access denied for user 'jean'@'%%' to database 'instelipost'")
2019-05-28 21:28:20,152 level=INFO message=127.0.0.1 - - [28/May/2019 21:28:20] "GET /list HTTP/1.1" 500 -
2019-05-28 21:28:21,650 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 67, in list
    cur = mysql.connection.cursor()
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1044, "Access denied for user 'jean'@'%%' to database 'instelipost'")
2019-05-28 21:28:21,652 level=INFO message=127.0.0.1 - - [28/May/2019 21:28:21] "GET /list HTTP/1.1" 500 -
2019-05-28 21:28:22,452 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 67, in list
    cur = mysql.connection.cursor()
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1044, "Access denied for user 'jean'@'%%' to database 'instelipost'")
2019-05-28 21:28:22,458 level=INFO message=127.0.0.1 - - [28/May/2019 21:28:22] "GET /list HTTP/1.1" 500 -
2019-05-28 21:28:22,655 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 67, in list
    cur = mysql.connection.cursor()
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1044, "Access denied for user 'jean'@'%%' to database 'instelipost'")
2019-05-28 21:28:22,657 level=INFO message=127.0.0.1 - - [28/May/2019 21:28:22] "GET /list HTTP/1.1" 500 -
2019-05-28 21:28:22,838 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 67, in list
    cur = mysql.connection.cursor()
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1044, "Access denied for user 'jean'@'%%' to database 'instelipost'")
2019-05-28 21:28:22,838 level=INFO message=127.0.0.1 - - [28/May/2019 21:28:22] "GET /list HTTP/1.1" 500 -
2019-05-28 21:28:23,006 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 67, in list
    cur = mysql.connection.cursor()
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1044, "Access denied for user 'jean'@'%%' to database 'instelipost'")
2019-05-28 21:28:23,008 level=INFO message=127.0.0.1 - - [28/May/2019 21:28:23] "GET /list HTTP/1.1" 500 -
2019-05-28 21:29:27,913 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-28 21:32:52,279 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-28 21:33:01,257 level=INFO message=127.0.0.1 - - [28/May/2019 21:33:01] "GET / HTTP/1.1" 200 -
2019-05-28 21:33:17,585 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-28 21:33:19,722 level=INFO message=127.0.0.1 - - [28/May/2019 21:33:19] "GET / HTTP/1.1" 404 -
2019-05-28 21:33:22,955 level=INFO message=127.0.0.1 - - [28/May/2019 21:33:22] "GET / HTTP/1.1" 404 -
2019-05-28 21:33:34,997 level=ERROR message=Not Found
2019-05-28 21:33:35,001 level=INFO message=127.0.0.1 - - [28/May/2019 21:33:35] "GET /list/2 HTTP/1.1" 200 -
2019-05-28 21:33:38,985 level=ERROR message=Not Found
2019-05-28 21:33:38,986 level=INFO message=127.0.0.1 - - [28/May/2019 21:33:38] "GET /list/1 HTTP/1.1" 200 -
2019-05-28 21:33:42,371 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 68, in list
    cur = mysql.connection.cursor()
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
  File "/home/jean/.local/lib/python3.5/site-packages/flask_mysqldb/__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/home/jean/.local/lib/python3.5/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1044, "Access denied for user 'jean'@'%%' to database 'instelipost'")
2019-05-28 21:33:42,375 level=INFO message=127.0.0.1 - - [28/May/2019 21:33:42] "GET /list HTTP/1.1" 500 -
2019-05-28 21:33:53,623 level=ERROR message=MySQL connection is NOT OK!
2019-05-28 21:33:53,625 level=INFO message=127.0.0.1 - - [28/May/2019 21:33:53] "POST /add HTTP/1.1" 200 -
2019-05-28 21:36:41,854 level=ERROR message=MySQL connection is NOT OK!
2019-05-28 21:36:41,855 level=INFO message=127.0.0.1 - - [28/May/2019 21:36:41] "POST /add HTTP/1.1" 200 -
2019-05-28 21:37:28,391 level=ERROR message=MySQL connection is NOT OK!
2019-05-28 21:37:28,393 level=INFO message=127.0.0.1 - - [28/May/2019 21:37:28] "POST /add HTTP/1.1" 200 -
2019-05-28 21:38:12,813 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-28 21:38:18,817 level=ERROR message=MySQL connection is NOT OK!
2019-05-28 21:38:18,821 level=INFO message=127.0.0.1 - - [28/May/2019 21:38:18] "POST /add HTTP/1.1" 200 -
2019-05-28 21:38:21,114 level=ERROR message=MySQL connection is NOT OK!
2019-05-28 21:38:21,117 level=INFO message=127.0.0.1 - - [28/May/2019 21:38:21] "POST /add HTTP/1.1" 200 -
2019-05-28 21:38:23,843 level=INFO message=127.0.0.1 - - [28/May/2019 21:38:23] "GET /list HTTP/1.1" 200 -
2019-05-28 21:38:26,497 level=INFO message=127.0.0.1 - - [28/May/2019 21:38:26] "GET /list HTTP/1.1" 200 -
2019-05-28 21:38:32,179 level=INFO message=127.0.0.1 - - [28/May/2019 21:38:32] "GET /list HTTP/1.1" 200 -
2019-05-28 21:39:35,524 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-28 21:39:39,482 level=ERROR message=MySQL connection is NOT OK!
2019-05-28 21:39:39,485 level=INFO message=127.0.0.1 - - [28/May/2019 21:39:39] "POST /add HTTP/1.1" 200 -
2019-05-28 21:54:20,127 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 80, in list
    'finish': item[6]
IndexError: tuple index out of range
2019-05-28 21:54:20,142 level=INFO message=127.0.0.1 - - [28/May/2019 21:54:20] "GET /list HTTP/1.1" 500 -
2019-05-28 21:54:22,210 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 80, in list
    'finish': item[6]
IndexError: tuple index out of range
2019-05-28 21:54:22,212 level=INFO message=127.0.0.1 - - [28/May/2019 21:54:22] "GET /list HTTP/1.1" 500 -
2019-05-28 21:54:30,081 level=INFO message=127.0.0.1 - - [28/May/2019 21:54:30] "GET / HTTP/1.1" 200 -
2019-05-28 21:54:35,904 level=ERROR message=Not Found
2019-05-28 21:54:35,905 level=INFO message=127.0.0.1 - - [28/May/2019 21:54:35] "GET /list/1 HTTP/1.1" 200 -
2019-05-28 21:55:12,444 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-28 22:57:18,370 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-28 22:57:24,111 level=INFO message=127.0.0.1 - - [28/May/2019 22:57:24] "GET / HTTP/1.1" 200 -
2019-05-28 22:57:29,173 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 80, in list
    'finish': item[6]
IndexError: tuple index out of range
2019-05-28 22:57:29,175 level=INFO message=127.0.0.1 - - [28/May/2019 22:57:29] "GET /list HTTP/1.1" 500 -
2019-05-28 22:58:16,687 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 80, in list
    'start': item[4],
IndexError: tuple index out of range
2019-05-28 22:58:16,688 level=INFO message=127.0.0.1 - - [28/May/2019 22:58:16] "GET /list HTTP/1.1" 500 -
2019-05-28 23:01:33,530 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 80, in list
    'finish': item[5]
IndexError: tuple index out of range
2019-05-28 23:01:33,532 level=INFO message=127.0.0.1 - - [28/May/2019 23:01:33] "GET /list HTTP/1.1" 500 -
2019-05-28 23:01:37,397 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 80, in list
    'finish': item[5]
IndexError: tuple index out of range
2019-05-28 23:01:37,401 level=INFO message=127.0.0.1 - - [28/May/2019 23:01:37] "GET /list HTTP/1.1" 500 -
2019-05-28 23:01:38,150 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 80, in list
    'finish': item[5]
IndexError: tuple index out of range
2019-05-28 23:01:38,162 level=INFO message=127.0.0.1 - - [28/May/2019 23:01:38] "GET /list HTTP/1.1" 500 -
2019-05-28 23:01:38,342 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 80, in list
    'finish': item[5]
IndexError: tuple index out of range
2019-05-28 23:01:38,343 level=INFO message=127.0.0.1 - - [28/May/2019 23:01:38] "GET /list HTTP/1.1" 500 -
2019-05-28 23:01:38,763 level=ERROR message=Exception on /list [GET]
Traceback (most recent call last):
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jean/.local/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jean/.local/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 80, in list
    'finish': item[5]
IndexError: tuple index out of range
2019-05-28 23:01:38,765 level=INFO message=127.0.0.1 - - [28/May/2019 23:01:38] "GET /list HTTP/1.1" 500 -
2019-05-28 23:01:53,127 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-28 23:01:55,339 level=INFO message=127.0.0.1 - - [28/May/2019 23:01:55] "GET /list HTTP/1.1" 200 -
2019-05-28 23:03:12,262 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-28 23:03:12,263 level=INFO message= * Restarting with stat
2019-05-28 23:03:12,432 level=WARNING message= * Debugger is active!
2019-05-28 23:03:12,433 level=INFO message= * Debugger PIN: 273-795-185
2019-05-28 23:03:14,991 level=INFO message=127.0.0.1 - - [28/May/2019 23:03:14] "GET /list HTTP/1.1" 200 -
2019-05-28 23:03:38,672 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/Desafio/app.py', reloading
2019-05-28 23:03:38,704 level=INFO message= * Restarting with stat
2019-05-28 23:03:38,876 level=WARNING message= * Debugger is active!
2019-05-28 23:03:38,876 level=INFO message= * Debugger PIN: 273-795-185
2019-05-28 23:03:39,884 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/Desafio/app.py', reloading
2019-05-28 23:03:39,933 level=INFO message= * Restarting with stat
2019-05-28 23:03:40,147 level=WARNING message= * Debugger is active!
2019-05-28 23:03:40,147 level=INFO message= * Debugger PIN: 273-795-185
2019-05-28 23:05:44,947 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-28 23:05:44,948 level=INFO message= * Restarting with stat
2019-05-28 23:05:45,105 level=WARNING message= * Debugger is active!
2019-05-28 23:05:45,106 level=INFO message= * Debugger PIN: 273-795-185
2019-05-28 23:05:55,029 level=ERROR message=MySQL connection is NOT OK!
2019-05-28 23:05:55,032 level=INFO message=127.0.0.1 - - [28/May/2019 23:05:55] "POST /add HTTP/1.1" 200 -
2019-05-29 02:21:39,157 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-29 02:21:39,159 level=INFO message= * Restarting with stat
2019-05-29 02:21:39,394 level=WARNING message= * Debugger is active!
2019-05-29 02:21:39,396 level=INFO message= * Debugger PIN: 170-319-462
2019-05-28 23:22:11,271 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-28 23:22:11,273 level=INFO message= * Restarting with stat
2019-05-28 23:22:11,530 level=WARNING message= * Debugger is active!
2019-05-28 23:22:11,531 level=INFO message= * Debugger PIN: 273-795-185
2019-05-29 02:36:39,838 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-29 02:36:39,840 level=INFO message= * Restarting with stat
2019-05-29 02:36:40,062 level=WARNING message= * Debugger is active!
2019-05-29 02:36:40,065 level=INFO message= * Debugger PIN: 314-326-057
2019-05-30 22:55:53,269 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-30 22:55:53,271 level=INFO message= * Restarting with stat
2019-05-30 22:55:53,535 level=WARNING message= * Debugger is active!
2019-05-30 22:55:53,536 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 22:56:02,718 level=INFO message=127.0.0.1 - - [30/May/2019 22:56:02] "GET / HTTP/1.1" 200 -
2019-05-30 22:58:46,081 level=ERROR message=MySQL connection is NOT OK!
2019-05-30 22:58:46,083 level=INFO message=127.0.0.1 - - [30/May/2019 22:58:46] "POST /add HTTP/1.1" 200 -
2019-05-30 22:58:59,469 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 22:58:59,511 level=INFO message= * Restarting with stat
2019-05-30 22:58:59,806 level=WARNING message= * Debugger is active!
2019-05-30 22:58:59,806 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 22:59:02,122 level=ERROR message=MySQL connection is NOT OK!
2019-05-30 22:59:02,124 level=INFO message=127.0.0.1 - - [30/May/2019 22:59:02] "POST /add HTTP/1.1" 200 -
2019-05-30 22:59:19,994 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 22:59:20,046 level=INFO message= * Restarting with stat
2019-05-30 22:59:20,436 level=WARNING message= * Debugger is active!
2019-05-30 22:59:20,439 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 22:59:21,773 level=ERROR message=MySQL connection is NOT OK!
2019-05-30 22:59:21,774 level=INFO message=127.0.0.1 - - [30/May/2019 22:59:21] "POST /add HTTP/1.1" 200 -
2019-05-30 23:02:24,647 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-30 23:02:24,650 level=INFO message= * Restarting with stat
2019-05-30 23:02:24,902 level=WARNING message= * Debugger is active!
2019-05-30 23:02:24,902 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:02:27,192 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:27] "GET /list HTTP/1.1" 500 -
2019-05-30 23:02:27,239 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:27] "GET /list?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2019-05-30 23:02:27,253 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:27] "GET /list?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2019-05-30 23:02:27,255 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:27] "GET /list?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2019-05-30 23:02:27,578 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:27] "GET /list?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2019-05-30 23:02:27,611 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:27] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:27,691 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:27] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:48,945 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-30 23:02:48,946 level=INFO message= * Restarting with stat
2019-05-30 23:02:49,202 level=WARNING message= * Debugger is active!
2019-05-30 23:02:49,202 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:02:51,725 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:51] "GET /list HTTP/1.1" 500 -
2019-05-30 23:02:51,774 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:51] "GET /list?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2019-05-30 23:02:51,780 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:51] "GET /list?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2019-05-30 23:02:51,783 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:51] "GET /list?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2019-05-30 23:02:51,913 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:51] "GET /list?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2019-05-30 23:02:51,938 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:51] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:53,693 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:53] "GET /list HTTP/1.1" 500 -
2019-05-30 23:02:53,715 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:53] "GET /list?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2019-05-30 23:02:53,717 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:53] "GET /list?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2019-05-30 23:02:53,741 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:53] "GET /list?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2019-05-30 23:02:53,802 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:53] "GET /list?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2019-05-30 23:02:53,804 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:53] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:53,881 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:53] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:54,323 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:54] "GET /list HTTP/1.1" 500 -
2019-05-30 23:02:54,379 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:54] "GET /list?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2019-05-30 23:02:54,387 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:54] "GET /list?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2019-05-30 23:02:54,398 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:54] "GET /list?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2019-05-30 23:02:54,502 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:54] "GET /list?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2019-05-30 23:02:54,513 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:54] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:54,578 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:54] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:54,894 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:54] "GET /list HTTP/1.1" 500 -
2019-05-30 23:02:54,964 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:54] "GET /list?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2019-05-30 23:02:54,982 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:54] "GET /list?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2019-05-30 23:02:54,983 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:54] "GET /list?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2019-05-30 23:02:55,097 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:55] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:55,106 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:55] "GET /list?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2019-05-30 23:02:55,158 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:55] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:55,463 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:55] "GET /list HTTP/1.1" 500 -
2019-05-30 23:02:55,539 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:55] "GET /list?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2019-05-30 23:02:55,556 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:55] "GET /list?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2019-05-30 23:02:55,559 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:55] "GET /list?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2019-05-30 23:02:55,642 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:55] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:55,650 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:55] "GET /list?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2019-05-30 23:02:55,699 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:55] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:55,978 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:55] "GET /list HTTP/1.1" 500 -
2019-05-30 23:02:56,045 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2019-05-30 23:02:56,049 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2019-05-30 23:02:56,051 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2019-05-30 23:02:56,142 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:56,151 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2019-05-30 23:02:56,199 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:56,439 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list HTTP/1.1" 500 -
2019-05-30 23:02:56,499 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2019-05-30 23:02:56,522 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2019-05-30 23:02:56,525 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2019-05-30 23:02:56,600 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2019-05-30 23:02:56,616 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:56,670 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:56,985 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:56] "GET /list HTTP/1.1" 500 -
2019-05-30 23:02:57,038 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:57] "GET /list?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2019-05-30 23:02:57,049 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:57] "GET /list?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2019-05-30 23:02:57,051 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:57] "GET /list?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2019-05-30 23:02:57,159 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:57] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:02:57,166 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:57] "GET /list?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2019-05-30 23:02:57,218 level=INFO message=127.0.0.1 - - [30/May/2019 23:02:57] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:03:19,894 level=INFO message=127.0.0.1 - - [30/May/2019 23:03:19] "GET /list HTTP/1.1" 500 -
2019-05-30 23:04:38,676 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-30 23:04:38,677 level=INFO message= * Restarting with stat
2019-05-30 23:04:38,796 level=WARNING message= * Debugger is active!
2019-05-30 23:04:38,797 level=INFO message= * Debugger PIN: 102-812-679
2019-05-30 23:04:44,438 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:44] "GET /list HTTP/1.1" 500 -
2019-05-30 23:04:44,491 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:44] "GET /list?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2019-05-30 23:04:44,498 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:44] "GET /list?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2019-05-30 23:04:44,503 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:44] "GET /list?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2019-05-30 23:04:44,661 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:44] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:04:44,669 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:44] "GET /list?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2019-05-30 23:04:44,728 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:44] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:04:45,516 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:45] "GET /list HTTP/1.1" 500 -
2019-05-30 23:04:45,535 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:45] "GET /list?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2019-05-30 23:04:45,543 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:45] "GET /list?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2019-05-30 23:04:45,552 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:45] "GET /list?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
2019-05-30 23:04:45,623 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:45] "GET /list?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
2019-05-30 23:04:45,635 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:45] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:04:45,684 level=INFO message=127.0.0.1 - - [30/May/2019 23:04:45] "GET /list?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2019-05-30 23:04:54,007 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-30 23:04:54,008 level=INFO message= * Restarting with stat
2019-05-30 23:04:54,264 level=WARNING message= * Debugger is active!
2019-05-30 23:04:54,265 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:06:04,626 level=ERROR message=ID not found!
2019-05-30 23:06:04,628 level=INFO message=127.0.0.1 - - [30/May/2019 23:06:04] "GET /list/1 HTTP/1.1" 200 -
2019-05-30 23:06:08,815 level=ERROR message=ID not found!
2019-05-30 23:06:08,816 level=INFO message=127.0.0.1 - - [30/May/2019 23:06:08] "GET /list/2 HTTP/1.1" 200 -
2019-05-30 23:06:12,356 level=ERROR message=ID not found!
2019-05-30 23:06:12,357 level=INFO message=127.0.0.1 - - [30/May/2019 23:06:12] "GET /list/3 HTTP/1.1" 200 -
2019-05-30 23:07:09,707 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:07:09,760 level=INFO message= * Restarting with stat
2019-05-30 23:07:10,011 level=WARNING message= * Debugger is active!
2019-05-30 23:07:10,012 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:07:11,971 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-30 23:07:11,972 level=INFO message= * Restarting with stat
2019-05-30 23:07:12,140 level=WARNING message= * Debugger is active!
2019-05-30 23:07:12,140 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:07:18,216 level=INFO message=127.0.0.1 - - [30/May/2019 23:07:18] "GET /list/1 HTTP/1.1" 200 -
2019-05-30 23:07:23,167 level=INFO message=127.0.0.1 - - [30/May/2019 23:07:23] "GET /list/ HTTP/1.1" 404 -
2019-05-30 23:07:30,282 level=INFO message=127.0.0.1 - - [30/May/2019 23:07:30] "GET /list/ HTTP/1.1" 404 -
2019-05-30 23:07:36,371 level=INFO message=127.0.0.1 - - [30/May/2019 23:07:36] "GET /list/1 HTTP/1.1" 200 -
2019-05-30 23:07:38,294 level=INFO message=127.0.0.1 - - [30/May/2019 23:07:38] "GET /list/2 HTTP/1.1" 200 -
2019-05-30 23:07:42,143 level=INFO message=127.0.0.1 - - [30/May/2019 23:07:42] "GET / HTTP/1.1" 200 -
2019-05-30 23:07:45,983 level=INFO message=127.0.0.1 - - [30/May/2019 23:07:45] "GET /list HTTP/1.1" 200 -
2019-05-30 23:08:04,751 level=ERROR message=MySQL connection is NOT OK!
2019-05-30 23:08:04,756 level=INFO message=127.0.0.1 - - [30/May/2019 23:08:04] "POST /add HTTP/1.1" 200 -
2019-05-30 23:08:35,900 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:08:35,931 level=INFO message= * Restarting with stat
2019-05-30 23:08:36,092 level=WARNING message= * Debugger is active!
2019-05-30 23:08:36,093 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:08:38,207 level=ERROR message=MySQL connection is NOT OK!
2019-05-30 23:08:38,208 level=INFO message=127.0.0.1 - - [30/May/2019 23:08:38] "POST /add HTTP/1.1" 200 -
2019-05-30 23:08:56,236 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:08:56,290 level=INFO message= * Restarting with stat
2019-05-30 23:08:56,447 level=WARNING message= * Debugger is active!
2019-05-30 23:08:56,447 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:09:09,549 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:09:09,588 level=INFO message= * Restarting with stat
2019-05-30 23:09:09,800 level=WARNING message= * Debugger is active!
2019-05-30 23:09:09,801 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:09:10,810 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:09:10,840 level=INFO message= * Restarting with stat
2019-05-30 23:09:11,063 level=WARNING message= * Debugger is active!
2019-05-30 23:09:11,065 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:09:14,389 level=ERROR message=MySQL connection is NOT OK!
2019-05-30 23:09:14,390 level=INFO message=127.0.0.1 - - [30/May/2019 23:09:14] "POST /add HTTP/1.1" 200 -
2019-05-30 23:09:42,321 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:09:42,351 level=INFO message= * Restarting with stat
2019-05-30 23:09:42,513 level=WARNING message= * Debugger is active!
2019-05-30 23:09:42,514 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:09:43,522 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:09:43,556 level=INFO message= * Restarting with stat
2019-05-30 23:09:43,733 level=WARNING message= * Debugger is active!
2019-05-30 23:09:43,733 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:09:44,744 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:09:44,777 level=INFO message= * Restarting with stat
2019-05-30 23:09:44,943 level=WARNING message= * Debugger is active!
2019-05-30 23:09:44,944 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:10:49,515 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:10:49,543 level=INFO message= * Restarting with stat
2019-05-30 23:10:49,714 level=WARNING message= * Debugger is active!
2019-05-30 23:10:49,715 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:10:50,724 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:10:50,753 level=INFO message= * Restarting with stat
2019-05-30 23:10:50,950 level=WARNING message= * Debugger is active!
2019-05-30 23:10:50,951 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:10:51,959 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:10:51,999 level=INFO message= * Restarting with stat
2019-05-30 23:10:52,177 level=WARNING message= * Debugger is active!
2019-05-30 23:10:52,178 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:11:21,423 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:11:21,455 level=INFO message= * Restarting with stat
2019-05-30 23:11:21,654 level=WARNING message= * Debugger is active!
2019-05-30 23:11:21,655 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:11:35,743 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:11:35,775 level=INFO message= * Restarting with stat
2019-05-30 23:11:35,962 level=WARNING message= * Debugger is active!
2019-05-30 23:11:35,963 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:11:50,068 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:11:50,101 level=INFO message= * Restarting with stat
2019-05-30 23:11:50,285 level=WARNING message= * Debugger is active!
2019-05-30 23:11:50,286 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:12:05,411 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:12:05,441 level=INFO message= * Restarting with stat
2019-05-30 23:12:05,622 level=WARNING message= * Debugger is active!
2019-05-30 23:12:05,623 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:12:08,587 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-30 23:12:08,588 level=INFO message= * Restarting with stat
2019-05-30 23:12:08,780 level=WARNING message= * Debugger is active!
2019-05-30 23:12:08,780 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:13:16,405 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:13:16,462 level=INFO message= * Restarting with stat
2019-05-30 23:13:16,628 level=WARNING message= * Debugger is active!
2019-05-30 23:13:16,629 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:14:39,116 level=INFO message=Cadastrado com Sucesso
2019-05-30 23:14:39,125 level=INFO message=127.0.0.1 - - [30/May/2019 23:14:39] "POST /add HTTP/1.1" 500 -
2019-05-30 23:14:50,442 level=INFO message=Cadastrado com Sucesso
2019-05-30 23:14:50,448 level=INFO message=127.0.0.1 - - [30/May/2019 23:14:50] "POST /add HTTP/1.1" 500 -
2019-05-30 23:16:34,646 level=INFO message=127.0.0.1 - - [30/May/2019 23:16:34] "POST /add HTTP/1.1" 500 -
2019-05-30 23:16:55,194 level=INFO message=Cadastrado com Sucesso
2019-05-30 23:16:55,205 level=INFO message=127.0.0.1 - - [30/May/2019 23:16:55] "POST /add HTTP/1.1" 500 -
2019-05-30 23:24:13,854 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:24:13,890 level=INFO message= * Restarting with stat
2019-05-30 23:24:14,096 level=WARNING message= * Debugger is active!
2019-05-30 23:24:14,098 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:26:12,125 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:26:12,157 level=INFO message= * Restarting with stat
2019-05-30 23:26:12,334 level=WARNING message= * Debugger is active!
2019-05-30 23:26:12,334 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:27:49,190 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:27:49,227 level=INFO message= * Restarting with stat
2019-05-30 23:27:49,407 level=WARNING message= * Debugger is active!
2019-05-30 23:27:49,407 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:27:55,843 level=INFO message=127.0.0.1 - - [30/May/2019 23:27:55] "POST /add HTTP/1.1" 500 -
2019-05-30 23:29:59,418 level=INFO message=127.0.0.1 - - [30/May/2019 23:29:59] "POST /add HTTP/1.1" 400 -
2019-05-30 23:30:28,294 level=INFO message=127.0.0.1 - - [30/May/2019 23:30:28] "POST /add HTTP/1.1" 400 -
2019-05-30 23:30:41,527 level=INFO message=127.0.0.1 - - [30/May/2019 23:30:41] "POST /add HTTP/1.1" 400 -
2019-05-30 23:32:14,734 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:32:14,772 level=INFO message= * Restarting with stat
2019-05-30 23:32:14,950 level=WARNING message= * Debugger is active!
2019-05-30 23:32:14,951 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:32:15,963 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:32:16,010 level=INFO message= * Restarting with stat
2019-05-30 23:32:16,262 level=WARNING message= * Debugger is active!
2019-05-30 23:32:16,262 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:32:18,578 level=ERROR message=MySQL connection is NOT OK!
2019-05-30 23:32:18,580 level=INFO message=127.0.0.1 - - [30/May/2019 23:32:18] "POST /add HTTP/1.1" 200 -
2019-05-30 23:32:29,046 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-30 23:32:29,047 level=INFO message= * Restarting with stat
2019-05-30 23:32:29,206 level=WARNING message= * Debugger is active!
2019-05-30 23:32:29,206 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:32:31,276 level=ERROR message=MySQL connection is NOT OK!
2019-05-30 23:32:31,280 level=INFO message=127.0.0.1 - - [30/May/2019 23:32:31] "POST /add HTTP/1.1" 200 -
2019-05-30 23:32:33,746 level=ERROR message=MySQL connection is NOT OK!
2019-05-30 23:32:33,748 level=INFO message=127.0.0.1 - - [30/May/2019 23:32:33] "POST /add HTTP/1.1" 200 -
2019-05-30 23:32:34,945 level=ERROR message=MySQL connection is NOT OK!
2019-05-30 23:32:34,946 level=INFO message=127.0.0.1 - - [30/May/2019 23:32:34] "POST /add HTTP/1.1" 200 -
2019-05-30 23:37:12,804 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:37:12,837 level=INFO message= * Restarting with stat
2019-05-30 23:37:13,032 level=WARNING message= * Debugger is active!
2019-05-30 23:37:13,033 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:37:18,071 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:37:18,116 level=INFO message= * Restarting with stat
2019-05-30 23:37:18,281 level=WARNING message= * Debugger is active!
2019-05-30 23:37:18,281 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:37:19,295 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:37:19,343 level=INFO message= * Restarting with stat
2019-05-30 23:37:19,518 level=WARNING message= * Debugger is active!
2019-05-30 23:37:19,519 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:37:20,530 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:37:20,588 level=INFO message= * Restarting with stat
2019-05-30 23:37:20,751 level=WARNING message= * Debugger is active!
2019-05-30 23:37:20,751 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:37:46,597 level=ERROR message=MySQL connection is NOT OK!
2019-05-30 23:37:46,602 level=INFO message=127.0.0.1 - - [30/May/2019 23:37:46] "POST /add HTTP/1.1" 200 -
2019-05-30 23:40:08,235 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:40:08,265 level=INFO message= * Restarting with stat
2019-05-30 23:40:08,452 level=WARNING message= * Debugger is active!
2019-05-30 23:40:08,452 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:40:25,031 level=ERROR message=MySQL connection is not OK!
2019-05-30 23:40:25,044 level=INFO message=127.0.0.1 - - [30/May/2019 23:40:25] "POST /add HTTP/1.1" 500 -
2019-05-30 23:41:25,109 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:41:25,184 level=INFO message= * Restarting with stat
2019-05-30 23:41:25,394 level=WARNING message= * Debugger is active!
2019-05-30 23:41:25,394 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:41:26,401 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:41:26,441 level=INFO message= * Restarting with stat
2019-05-30 23:41:26,683 level=WARNING message= * Debugger is active!
2019-05-30 23:41:26,684 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:41:27,828 level=INFO message=127.0.0.1 - - [30/May/2019 23:41:27] "POST /add HTTP/1.1" 500 -
2019-05-30 23:42:16,123 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:42:16,154 level=INFO message= * Restarting with stat
2019-05-30 23:42:16,359 level=WARNING message= * Debugger is active!
2019-05-30 23:42:16,360 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:42:19,108 level=ERROR message=MySQL connection is not OK!
2019-05-30 23:42:19,122 level=INFO message=127.0.0.1 - - [30/May/2019 23:42:19] "POST /add HTTP/1.1" 500 -
2019-05-30 23:42:44,551 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:42:44,587 level=INFO message= * Restarting with stat
2019-05-30 23:43:07,101 level=INFO message= * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2019-05-30 23:43:07,102 level=INFO message= * Restarting with stat
2019-05-30 23:43:07,272 level=WARNING message= * Debugger is active!
2019-05-30 23:43:07,272 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:43:09,162 level=ERROR message=Submited Successfull!
2019-05-30 23:43:09,177 level=INFO message=127.0.0.1 - - [30/May/2019 23:43:09] "POST /add HTTP/1.1" 500 -
2019-05-30 23:43:34,393 level=ERROR message=Submited Successfull!
2019-05-30 23:43:34,420 level=INFO message=127.0.0.1 - - [30/May/2019 23:43:34] "POST /add HTTP/1.1" 500 -
2019-05-30 23:45:25,551 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:45:25,625 level=INFO message= * Restarting with stat
2019-05-30 23:45:25,871 level=WARNING message= * Debugger is active!
2019-05-30 23:45:25,873 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:45:26,893 level=ERROR message=MySQL connection is not OK!
2019-05-30 23:45:26,901 level=INFO message=127.0.0.1 - - [30/May/2019 23:45:26] "POST /add HTTP/1.1" 500 -
2019-05-30 23:50:02,401 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:50:02,439 level=INFO message= * Restarting with stat
2019-05-30 23:50:02,654 level=WARNING message= * Debugger is active!
2019-05-30 23:50:02,655 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:50:14,744 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:50:14,815 level=INFO message= * Restarting with stat
2019-05-30 23:50:14,998 level=WARNING message= * Debugger is active!
2019-05-30 23:50:14,999 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:50:17,876 level=ERROR message=MySQL connection is not OK!
2019-05-30 23:50:17,917 level=INFO message=127.0.0.1 - - [30/May/2019 23:50:17] "POST /add HTTP/1.1" 500 -
2019-05-30 23:50:34,153 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:50:34,216 level=INFO message= * Restarting with stat
2019-05-30 23:50:34,439 level=WARNING message= * Debugger is active!
2019-05-30 23:50:34,441 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:50:35,739 level=ERROR message=MySQL connection is not OK!
2019-05-30 23:50:35,772 level=INFO message=127.0.0.1 - - [30/May/2019 23:50:35] "POST /add HTTP/1.1" 500 -
2019-05-30 23:50:39,513 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:50:39,576 level=INFO message= * Restarting with stat
2019-05-30 23:50:39,780 level=WARNING message= * Debugger is active!
2019-05-30 23:50:39,780 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:50:40,789 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:50:40,837 level=INFO message= * Restarting with stat
2019-05-30 23:50:41,069 level=WARNING message= * Debugger is active!
2019-05-30 23:50:41,070 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:50:47,134 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:50:47,183 level=INFO message= * Restarting with stat
2019-05-30 23:50:47,446 level=WARNING message= * Debugger is active!
2019-05-30 23:50:47,447 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:50:47,873 level=ERROR message=MySQL connection is not OK!
2019-05-30 23:50:47,881 level=INFO message=127.0.0.1 - - [30/May/2019 23:50:47] "POST /add HTTP/1.1" 400 -
2019-05-30 23:51:42,928 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:51:42,976 level=INFO message= * Restarting with stat
2019-05-30 23:51:43,241 level=WARNING message= * Debugger is active!
2019-05-30 23:51:43,244 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:51:54,906 level=ERROR message=MySQL connection is not OK!
2019-05-30 23:51:54,915 level=INFO message=127.0.0.1 - - [30/May/2019 23:51:54] "POST /add HTTP/1.1" 400 -
2019-05-30 23:52:08,441 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:52:08,480 level=INFO message= * Restarting with stat
2019-05-30 23:52:08,671 level=WARNING message= * Debugger is active!
2019-05-30 23:52:08,672 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:52:09,679 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:52:09,724 level=INFO message= * Restarting with stat
2019-05-30 23:52:09,998 level=WARNING message= * Debugger is active!
2019-05-30 23:52:10,003 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:52:13,021 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:52:13,053 level=INFO message= * Restarting with stat
2019-05-30 23:52:13,282 level=WARNING message= * Debugger is active!
2019-05-30 23:52:13,283 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:52:14,290 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:52:14,320 level=INFO message= * Restarting with stat
2019-05-30 23:52:14,500 level=WARNING message= * Debugger is active!
2019-05-30 23:52:14,501 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:52:14,985 level=ERROR message=MySQL connection is not OK!
2019-05-30 23:52:14,995 level=INFO message=127.0.0.1 - - [30/May/2019 23:52:14] "POST /add HTTP/1.1" 400 -
2019-05-30 23:52:32,062 level=ERROR message=MySQL connection is not OK!
2019-05-30 23:52:32,066 level=INFO message=127.0.0.1 - - [30/May/2019 23:52:32] "POST /add HTTP/1.1" 400 -
2019-05-30 23:53:19,884 level=ERROR message=MySQL connection is not OK!
2019-05-30 23:53:19,886 level=INFO message=127.0.0.1 - - [30/May/2019 23:53:19] "POST /add HTTP/1.1" 400 -
2019-05-30 23:56:25,139 level=ERROR message=MySQL connection is not OK!
2019-05-30 23:56:25,143 level=INFO message=127.0.0.1 - - [30/May/2019 23:56:25] "POST /add HTTP/1.1" 400 -
2019-05-30 23:59:12,199 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:59:12,244 level=INFO message= * Restarting with stat
2019-05-30 23:59:12,603 level=WARNING message= * Debugger is active!
2019-05-30 23:59:12,604 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:59:13,612 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-30 23:59:13,643 level=INFO message= * Restarting with stat
2019-05-30 23:59:13,822 level=WARNING message= * Debugger is active!
2019-05-30 23:59:13,823 level=INFO message= * Debugger PIN: 273-795-185
2019-05-30 23:59:14,370 level=ERROR message=MySQL connection is not OK!
2019-05-30 23:59:14,387 level=INFO message=127.0.0.1 - - [30/May/2019 23:59:14] "POST /add HTTP/1.1" 500 -
2019-05-31 00:06:06,621 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-31 00:06:06,659 level=INFO message= * Restarting with stat
2019-05-31 00:06:06,879 level=WARNING message= * Debugger is active!
2019-05-31 00:06:06,880 level=INFO message= * Debugger PIN: 273-795-185
2019-05-31 00:07:39,773 level=ERROR message=MySQL connection is not OK!
2019-05-31 00:07:39,796 level=INFO message=127.0.0.1 - - [31/May/2019 00:07:39] "POST /add HTTP/1.1" 500 -
2019-05-31 00:08:08,960 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-31 00:08:08,993 level=INFO message= * Restarting with stat
2019-05-31 00:08:09,180 level=WARNING message= * Debugger is active!
2019-05-31 00:08:09,181 level=INFO message= * Debugger PIN: 273-795-185
2019-05-31 00:08:18,249 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-31 00:08:18,282 level=INFO message= * Restarting with stat
2019-05-31 00:08:18,466 level=WARNING message= * Debugger is active!
2019-05-31 00:08:18,467 level=INFO message= * Debugger PIN: 273-795-185
2019-05-31 00:08:19,653 level=ERROR message=MySQL connection is NOT OK!
2019-05-31 00:08:19,655 level=INFO message=127.0.0.1 - - [31/May/2019 00:08:19] "POST /add HTTP/1.1" 200 -
2019-05-31 00:08:45,014 level=ERROR message=MySQL connection is NOT OK!
2019-05-31 00:08:45,016 level=INFO message=127.0.0.1 - - [31/May/2019 00:08:45] "POST /add HTTP/1.1" 200 -
2019-05-31 00:09:27,734 level=INFO message=127.0.0.1 - - [31/May/2019 00:09:27] "GET /list HTTP/1.1" 200 -
2019-05-31 00:09:32,511 level=INFO message=127.0.0.1 - - [31/May/2019 00:09:32] "GET /list/1 HTTP/1.1" 200 -
2019-05-31 00:09:40,968 level=INFO message=127.0.0.1 - - [31/May/2019 00:09:40] "GET /list/2 HTTP/1.1" 200 -
2019-05-31 00:09:44,426 level=INFO message=127.0.0.1 - - [31/May/2019 00:09:44] "GET /list/3 HTTP/1.1" 200 -
2019-05-31 00:10:23,530 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-31 00:10:23,560 level=INFO message= * Restarting with stat
2019-05-31 00:10:23,732 level=WARNING message= * Debugger is active!
2019-05-31 00:10:23,733 level=INFO message= * Debugger PIN: 273-795-185
2019-05-31 00:10:31,452 level=INFO message=MySQL connection is OK!
2019-05-31 00:10:31,454 level=INFO message=127.0.0.1 - - [31/May/2019 00:10:31] "GET /status HTTP/1.1" 200 -
2019-05-31 00:10:47,964 level=INFO message= * Detected change in '/home/jean/Documents/personal/Intelispost/desafio/app.py', reloading
2019-05-31 00:10:48,036 level=INFO message= * Restarting with stat
2019-05-31 00:10:48,248 level=WARNING message= * Debugger is active!
2019-05-31 00:10:48,249 level=INFO message= * Debugger PIN: 273-795-185
